online_magazine/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('titles/', include('magazine.urls', namespace='magazine.magazine')),
]

online_magazine/magazine/urls.py
from django.urls import path
from .views import article_view, change_article, delete_article

app_name = 'magazine'

urlpatterns = [
    path('', article_view, name='article_view'),
    path('change/', change_article, name='change_article'),
    path('delete/', delete_article, name='delete_article'),
    path('<int:pk>/', article_view, name='article_view'),
]

online_magazine/magazine/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(verbose_name='Заголовок', max_length=50)
    main_body = models.TextField(verbose_name='Статья')

    def __str__(self) -> str:
        return f'{self.title}'

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('magazine:article_view', kwargs={'pk': self.pk})

online_magazine/magazine/views.py
from django.shortcuts import render
from .models import Article


# Create your views here.

def article_view(request, pk=None):
    if pk:
        template_ = 'full_title.html'
        current_article = Article.objects.get(pk=pk)
        context = {
            'current_article': current_article
        }
        return render(request, template_name=template_, context=context)
    else:
        template_ = 'titles.html'
        articles = Article.objects.all()
        context = {
            'arts': articles
        }
        return render(request, template_name=template_, context=context)


def change_article(request) -> render:
    template_ = 'titles.html'
    articles = Article.objects.all()

    context = {
        'arts': articles
    }
    for i in articles:
        if str(i.pk) not in i.title:
            i.title = f'{i.title} - {i.pk}'
            i.save()

    return render(request, template_name=template_, context=context)

def delete_article(request) -> render:
    template_ = 'titles.html'
    articles = Article.objects.all()

    context = {
        'arts': articles
    }
    for i in articles:
        if i.pk % 2 == 1:
            i.delete()

    return render(request, template_name=template_, context=context)

online_magazine/magazine/templates/full_title.html
{% extends 'layout/base.html' %}

{% block content %}
    <h1>{{current_article.title}}</h1>
    <p>{{current_article.main_body}}</p>
    <a href="{% url 'magazine:article_view' %}"><button style="padding:8px; background-color:black; color:white; border-radius:10px;'">Обратно</button></a>
{% endblock content %}

online_magazine/magazine/templates/layout/base.html
{% include 'layout/nav.html' %}
{% block title %}
    Статьи
{% endblock title %}
{% block content %}
{% endblock content %}

online_magazine/magazine/templates/layout/nav.html
<nav>
    <div style="display:flex; display-direction:row; gap:10px; background-color:grey; align-items:center;">
        <a href="{% url 'magazine:article_view' %}"><p>Заголовки</p></a>
        <a href="/admin"><p>Админка</p></a>
    </div>
</nav>т

online_magazine/magazine/templates/titles.html
{% extends 'layout/base.html' %}

{% block content %}
    {% for i in arts %}
        <div>
            <h4> {{i.title}} </h4>
            <a href="{{i.get_absolute_url}}"><buttun>перейти</buttun></a>
        </div>
    {% endfor %}
    <a href="{% url 'magazine:change_article' %}">«заголовок (id)»</a>
    <a href="{% url 'magazine:delete_article' %}">удалить</a>
{% endblock content %}